name: OAuthRegression


on:
  push: {}
#  schedule:
#    - cron: '0 7 * * 1,2,3,4,5'

jobs:
  playwright:
    name: OAuth regression tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.42.0-jammy
    env:
      API_KEY: ${{ secrets.API_KEY_QA }}
#      QASE_TOKEN: ${{ secrets.QS_TO_API_TOKEN }}
    strategy:
      matrix:
        browser: [remote_chrome]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'